# -*- coding: utf-8 -*-
"""Coding practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IR7scPjTTBmFsYBgufXlAbwfU5-_1NVs
"""

#problem 1
#Watermelon problem
w=int(input("w "))
if w>2 and w%2==0:
  print("yes")
else:
  print("no")

#way to long words prblm

no_of_words = int(input())

for _ in range(no_of_words):
    word = input().strip()
    if len(word) > 10:
        print(f"{word[0]}{len(word) - 2}{word[-1]}")
    else:
        print(word)

#sample code
print("hello world")

#hackerrank runup problem
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    arr1 = set(arr)
    arr2 = sorted(arr1)
    print(arr2[-2])