# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IR7scPjTTBmFsYBgufXlAbwfU5-_1NVs
"""

w=int(input("w "))
if w>2 and w%2==0:
  print("yes")
else:
  print("no")